force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <description>The Apex Class which spawned the current log record.</description>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <inlineHelpText>Details the current execution context when the log was generated.
Displays a System.Quiddity value: 
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_Quiddity.htm#topic-title</inlineHelpText>
    <label>Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <inlineHelpText>Indicates the severity of the log message. Values are derived from the System.LoggingLevel enum:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm</inlineHelpText>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>FINE</fullName>
            </value>
            <value>
                <fullName>FINER</fullName>
            </value>
            <value>
                <fullName>FINEST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/LoggedAt__c.field-meta.xml
<CustomField>
    <fullName>LoggedAt__c</fullName>
    <description>The Date/Time that the message was logged. This may differ slightly from the CreatedDate, depending on the publishing method</description>
    <label>Logged At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/LoggedBy__c.field-meta.xml
<CustomField>
    <fullName>LoggedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates the user that requested the Log. This may differ from the &quot;Created By&quot; user, if the log was published via platform event.</description>
    <label>Logged By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Ordinal__c.field-meta.xml
<CustomField>
    <fullName>Ordinal__c</fullName>
    <inlineHelpText>Indicates the order in which logs in the same transaction were inserted (beginning with 1).</inlineHelpText>
    <label>Ordinal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/RelatedRecordId__c.field-meta.xml
<CustomField>
    <fullName>RelatedRecordId__c</fullName>
    <description>The 18-digit Salesforce Id of the record most closely related to the current log.</description>
    <label>Related Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Contains optional information about where the log originated. Ex., a specific managed package, or a specific business process.</description>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <description>An identifier unique to each apex transaction. Use this to group logs from the same transaction together.</description>
    <label>Transaction</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogSetting__c/fields/Threshold__c.field-meta.xml
<CustomField>
    <fullName>Threshold__c</fullName>
    <defaultValue>&quot;NONE&quot;</defaultValue>
    <description>Possible values correspond with the standard LoggingLevel Enum:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm
Unfortunately, picklists are not available for Custom Settings.</description>
    <inlineHelpText>Possible values:
NONE: No logging.
ERROR: Error and exception logging.
WARN: Warning logging.
INFO: Informational logging.
DEBUG: User-specified debug logging.
FINE: High level of logging.
FINER: Higher level of logging than FINE.
FINEST: Highest level of logging.</inlineHelpText>
    <label>Threshold</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Logger.cls
global without sharing virtual class Logger {
    // Static Logger variables
    @TestVisible
    static List<Log__c> pendingLogs = new List<Log__c>(); 
    static LogPublisher configuredPublisher = Logger.getConfiguredPublisher(); 
    static Integer ordinal = 1;
    static System.LoggingLevel threshold = Logger.getThreshold();
    // Constants
    static final String TRANSACTION_ID = System.Request.getCurrent()?.getRequestId();

    // Log-specific members
    Type apexClass;
    Id relatedRecordId; 
    String source;

    // **** VIRTUAL **** // 
    global virtual Log__c generateLog(System.LoggingLevel level, Object body) {
        return new Log__c(
            ApexClass__c = this.apexClass?.getName(),
            Body__c = String.valueOf(body),
            Context__c = System.Request.getCurrent()?.getQuiddity()?.name(),
            Level__c = level?.name(),
            LoggedAt__c = DateTime.now(),
            LoggedBy__c = UserInfo.getUserId(),
            Ordinal__c = ordinal++,
            RelatedRecordId__c = this.relatedRecordId,
            Source__c = this.source,
            StackTrace__c = this.generateStackTrace(),
            Transaction__c = TRANSACTION_ID
        ); 
    }

    global virtual Logger log(System.LoggingLevel level, Object body) {
        if (this.shouldLog(level)) {
            // * Generate a Log__c record and add to pendingLogs
            Log__c log = this.generateLog(level, body);
            pendingLogs?.add(log); 
        }
        return this;
    }

    global virtual Logger publish(LogPublisher publisher) {
        publisher?.publish(pendingLogs);
        pendingLogs?.clear(); 
        return this; 
    }

    // **** PUBLIC **** // 
    global Logger error(Object body) {
        return this.log(System.LoggingLevel.ERROR, body); 
    }

    global Logger warn(Object body) {
        return this.log(System.LoggingLevel.WARN, body); 
    }

    global Logger info(Object body) {
        return this.log(System.LoggingLevel.INFO, body); 
    }

    global Logger debug(Object body) {
        return this.log(System.LoggingLevel.DEBUG, body); 
    }

    global Logger fine(Object body) {
        return this.log(System.LoggingLevel.FINE, body); 
    }

    global Logger finer(Object body) {
        return this.log(System.LoggingLevel.FINER, body); 
    }

    global Logger finest(Object body) {
        return this.log(System.LoggingLevel.FINEST, body); 
    }

    global Logger publish() {
        // Default to the configured publishing method from Custom Settings
        return this.publish(configuredPublisher); 
    }

    global Logger setApexClass(Type apexClass) {
        this.apexClass = apexClass;
        return this; 
    }

    global Logger setRecordId(Id recordId) {
        this.relatedRecordId = recordId; 
        return this; 
    }

    global Logger setSource(String source) {
        this.source = source;
        return this; 
    }

    // **** PRIVATE **** // 
    private String generateStackTrace() {
        return new LogException()?.sourceStackTrace();
    }

    private Boolean meetsThreshold(System.LoggingLevel level) {
        // Returns true if the level meets/exceeds the threshold
        // With the exception of NONE - which has an ordinal of 0, and should never be valid
        Integer currentSev = (level != null) ? level?.ordinal() : 0; 
        Integer thresholdSev = (threshold != null) ? threshold?.ordinal() : 0;
        System.debug('meetsThreshold() -> currentSev: ' + currentSev + '. thresholdSev: ' + thresholdSev);
        return thresholdSev != 0 && currentSev >= thresholdSev; 
    }

    private Boolean shouldLog(System.LoggingLevel level) {
        // Returns true if Logging is enabled for the current user, 
        // and if the level meets/exceeds the defined threshold
        Boolean isEnabled = LogSetting__c.getInstance()?.Enabled__c == true; 
        Boolean meetsThreshold = this.meetsThreshold(level);
        System.debug('Is Enabled: ' + isEnabled + '. Meets Threshold? ' + meetsThreshold);
        return isEnabled && meetsThreshold; 
    }

    // **** STATIC **** // 
    static System.LoggingLevel getThreshold() {
        // Returns the Threshold__c value expressed as a LoggingLevel enum
        // Defaults to NONE if illegal or missing values configured
        try {
            LogSetting__c settings = LogSetting__c.getInstance();
            String thresholdName = settings?.Threshold__c?.toUpperCase();
            System.LoggingLevel threshold = System.LoggingLevel.valueOf(thresholdName);
            return threshold != null ? threshold : System.LoggingLevel.NONE;
        } catch (Exception error) {
            // Enum.valueOf() throws errors for illegal values
            return System.LoggingLevel.NONE;
        }
    }

    static LogPublisher getConfiguredPublisher() {
        // TODO: Get from CMDT
        LogPublisher publisher = new LogDmlPublisher();
        return publisher; 
    }
    
    // **** INNER **** // 
    global interface LogPublisher {
        void publish(List<Log__c> logs);
    }

    private class LogException extends Exception {
        // This exception will never be thrown - used to generate a stack trace string for log messages
        final String loggerPrefix = 'Class.' + Logger.class?.getName() + '.';

		private String sourceStackTrace() {
            // Returns a stack trace string w/out Logger class internals
            // This allows callers to view the stack trace up until they called the logger method
			List<String> stackTraceLines = new List<String>();
			for (String stackTraceLine : this.getStackTraceString()?.split('\n')) {
				if (!stackTraceLine?.startsWith(this.loggerPrefix)) {
					stackTraceLines.add(stackTraceLine);
				}
			}
			return String.join(stackTraceLines, '\n');
		}
	}
}