force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <inlineHelpText>Indicates the severity of the log message. Values are derived from the System.LoggingLevel enum:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm</inlineHelpText>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>FINE</fullName>
            </value>
            <value>
                <fullName>FINER</fullName>
            </value>
            <value>
                <fullName>FINEST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/LoggedFrom__c.field-meta.xml
<CustomField>
    <fullName>LoggedFrom__c</fullName>
    <description>The component (ex., Logged From) which spawned the current log record.</description>
    <label>Logged From</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/RelatedRecordId__c.field-meta.xml
<CustomField>
    <fullName>RelatedRecordId__c</fullName>
    <description>The 18-digit Salesforce Id of the record most closely related to the current log.</description>
    <label>Related Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Contains optional information about where the log originated. Ex., a specific managed package, or a specific business process.</description>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LwcLoggerTest.cls
@IsTest
private class LwcLoggerTest {
	@IsTest
	static void shouldLogWithAdvancedDetails() {
		LogInput input = new LogInput();
		input.body = 'This is a test';
		input.level = System.LoggingLevel.ERROR?.name();
		input.loggedFrom = 'c-my-lwc';
		input.relatedRecordId = UserInfo.getUserId();
		input.source = 'fooBarLwc';

		Test.startTest();
		LwcLogger.log(JSON.serialize(input));
		Test.stopTest();

		List<Log__c> logs = LwcLoggerTest.getLogs();
		Assert.areEqual(1, logs?.size(), 'Wrong # of Logs created');
		Log__c log = logs[0];
		Assert.areEqual(input?.body, log?.Body__c, 'Wrong Level');
		Assert.areEqual(input?.level, log?.Level__c, 'Wrong Level');
		Assert.areEqual(input?.loggedFrom, log?.LoggedFrom__c, 'Wrong LoggedFrom');
		Assert.areEqual(input?.relatedRecordId, log?.RelatedRecordId__c, 'Wrong RelatedRecordId');
		Assert.areEqual(input?.source, log?.Source__c, 'Wrong Source');
	}

	@IsTest
	static void shouldLogWithMinimalDetail() {
		LogInput input = new LogInput();
		input.body = 'This is a test';
		input.level = System.LoggingLevel.ERROR?.name();

		Test.startTest();
		LwcLogger.log(JSON.serialize(input));
		Test.stopTest();

		List<Log__c> logs = LwcLoggerTest.getLogs();
		Assert.areEqual(1, logs?.size(), 'Wrong # of Logs created');
		Log__c log = logs[0];
		Assert.areEqual(input?.body, log?.Body__c, 'Wrong Level');
		Assert.areEqual(input?.level, log?.Level__c, 'Wrong Level');
		Assert.isNull(log?.LoggedFrom__c, 'LoggedFrom was set, but how?');
		Assert.isNull(log?.RelatedRecordId__c, 'RelatedRecordId was set, but how?');
		Assert.isNull(log?.Source__c, 'Source was set, but how?');
	}

	@IsTest
	static void shouldHandleInvalidPayload() {
		String badPayload = 'abcd1234';
		Exception error;

		Test.startTest();
		try {
			LwcLogger.log(badPayload);
		} catch (AuraHandledException caughtError) {
			error = caughtError;
		}
		Test.stopTest();

		Assert.isNotNull(error, 'Error was not thrown/caught for a bad payload');
	}

	// **** HELPER **** //
	@TestSetup
	static void setup() {
		LogTestUtils.enableLogging(System.LoggingLevel.FINEST);
	}

	static List<Log__c> getLogs() {
		return [SELECT Id, LoggedFrom__c, Body__c, Level__c, RelatedRecordId__c, Source__c FROM Log__c];
	}
}