force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <inlineHelpText>Indicates the severity of the log message. Values are derived from the System.LoggingLevel enum:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm</inlineHelpText>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>FINE</fullName>
            </value>
            <value>
                <fullName>FINER</fullName>
            </value>
            <value>
                <fullName>FINEST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/RelatedRecordId__c.field-meta.xml
<CustomField>
    <fullName>RelatedRecordId__c</fullName>
    <description>The 18-digit Salesforce Id of the record most closely related to the current log.</description>
    <label>Related Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LogRelatedListControllerTest.cls
@IsTest 
private class LogRelatedListControllerTest {
    @IsTest 
    static void shouldReturnRelatedLogs() {
        Account account = LogRelatedListControllerTest.getAccount(); 

        Test.startTest();
        List<Log__c> logs = LogRelatedListController.getLogs(account?.Id);
        Test.stopTest();

        Assert.areEqual(NUM_TEST_LOGS, logs?.size(), 'Wrong # of logs');
        for (Log__c log : logs) {
            Assert.areEqual(account?.Id, log?.RelatedRecordId__c, 'Wrong Record Id'); 
        }
    }

    @IsTest 
    static void shouldHandleNullId() {
        Account account = LogRelatedListControllerTest.getAccount();
        Id recordId = null; 

        Test.startTest();
        Exception error; 
        try {
            List<Log__c> logs = LogRelatedListController.getLogs(recordId);
        } catch (AuraHandledException caughtError) {
            error = caughtError;
        }
        Test.stopTest();

        Assert.areNotEqual(null, error, 'An error was not thrown'); 
    }

    // **** HELPER **** // 
    static final Integer NUM_TEST_LOGS = 200; 

    @TestSetup 
    static void setup() {
        // Create an Account
        Account account = new Account(Name = 'Test Account');
        insert account;
        // Create logs related to the Account
        List<Log__c> logs = new List<Log__c>();
        for (Integer i = 0; i < NUM_TEST_LOGS; i++) {
            Log__c log = new Log__c(
                Body__c = 'Test Log #' + i,
                Level__c = System.LoggingLevel.FINEST?.name(),
                RelatedRecordId__c = account?.Id
            ); 
            logs?.add(log);
        }
        insert logs;
    }

    static Account getAccount() {
        List<Account> accounts = [SELECT Id FROM Account ORDER BY CreatedDate DESC LIMIT 1];
        return accounts?.isEmpty() ? null : accounts[0];
    }
}