force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Contains an optional value which categorizes the log. Ex., a specific managed package, or a specific business process.</description>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <inlineHelpText>Details the current execution context when the log was generated.
Displays a System.Quiddity value: 
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_Quiddity.htm#topic-title</inlineHelpText>
    <label>Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <inlineHelpText>Indicates the severity of the log message. Values are derived from the System.LoggingLevel enum:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm</inlineHelpText>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>FINE</fullName>
            </value>
            <value>
                <fullName>FINER</fullName>
            </value>
            <value>
                <fullName>FINEST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/LoggedAt__c.field-meta.xml
<CustomField>
    <fullName>LoggedAt__c</fullName>
    <description>The Date/Time that the message was logged. This may differ slightly from the CreatedDate, depending on the publishing method</description>
    <label>Logged At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/LoggedBy__c.field-meta.xml
<CustomField>
    <fullName>LoggedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates the user that requested the Log. This may differ from the &quot;Created By&quot; user, if the log was published via platform event.</description>
    <label>Logged By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/LoggedFrom__c.field-meta.xml
<CustomField>
    <fullName>LoggedFrom__c</fullName>
    <description>The component (ex., Logged From) which spawned the current log record.</description>
    <label>Logged From</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Ordinal__c.field-meta.xml
<CustomField>
    <fullName>Ordinal__c</fullName>
    <inlineHelpText>Indicates the order in which logs in the same transaction were inserted (beginning with 1).</inlineHelpText>
    <label>Ordinal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/RelatedRecordId__c.field-meta.xml
<CustomField>
    <fullName>RelatedRecordId__c</fullName>
    <description>The 18-digit Salesforce Id of the record most closely related to the current log.</description>
    <label>Related Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <description>An identifier unique to each apex transaction. Use this to group logs from the same transaction together.</description>
    <label>Transaction</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/LogEvent__e.object-meta.xml
<CustomObject>
    <description>Contains Log data to be inserted asynchronously, via its platform event trigger.
Publish immediately behavior guarantees that logs published using this event will be captured, regardless of rollbacks and uncaught exceptions.</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogEvent__e/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <description>Maps to the Log field of the same name.</description>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Contains an optional value which categorizes the log. Ex., a specific managed package, or a specific business process. Maps to the Log field of the same name.</description>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <description>Details the current execution context when the log was generated. Maps to the Log field of the same name.
Displays a System.Quiddity value: 
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_Quiddity.htm#topic-title</description>
    <label>Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Indicates the severity of the log message.  Maps to the Log field of the same name. Values are derived from the System.LoggingLevel enum:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm</description>
    <label>Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/LoggedAt__c.field-meta.xml
<CustomField>
    <fullName>LoggedAt__c</fullName>
    <description>The Date/Time that the message was logged. This may differ slightly from the CreatedDate, depending on the publishing method. Maps to the Log field of the same name.</description>
    <label>Logged At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/LoggedBy__c.field-meta.xml
<CustomField>
    <fullName>LoggedBy__c</fullName>
    <description>Indicates the user that requested the Log. This may differ from the &quot;Created By&quot; user, if the log was published via platform event. Maps to the Log field of the same name.</description>
    <label>Logged By</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/LoggedFrom__c.field-meta.xml
<CustomField>
    <fullName>LoggedFrom__c</fullName>
    <description>The component (ex., Logged From) which spawned the current log record. Maps to the Log field of the same name.</description>
    <label>Logged From</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Ordinal__c.field-meta.xml
<CustomField>
    <description>Indicates the order in which logs in the same transaction were inserted (beginning with 1). Maps to the Log field of the same name.</description>
    <fullName>Ordinal__c</fullName>
    <label>Ordinal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/RelatedRecordId__c.field-meta.xml
<CustomField>
    <fullName>RelatedRecordId__c</fullName>
    <description>The 18-digit Salesforce Id of the record most closely related to the current log. Maps to the Log field of the same name.</description>
    <label>Related Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/StackTrace__c.field-meta.xml
<CustomField>
    <description>Maps to the Log field of the same name.</description>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <description>An identifier unique to each apex transaction. Use this to group logs from the same transaction together. Maps to the Log field of the same name.</description>
    <label>Transaction</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LogEventTriggerTest.cls
@IsTest 
private class LogEventTriggerTest {
    @IsTest 
    static void shouldCreateLogs() {
        for (Integer i = 0; i < 200; i++) {
            new Logger().info('Hello world');
        }
        List<LogEvent__e> events = (List<LogEvent__e>) JSON.deserialize(
            JSON.serialize(Logger.pendingLogs), 
            List<LogEvent__e>.class
        );

        Test.startTest();
        EventBus.publish(events);
        Test.getEventBus()?.deliver();
        Test.stopTest();

        List<Log__c> logs = LogEventTriggerTest.getLogs();
        Assert.areEqual(events?.size(), logs?.size(), 'Wrong # of Logs');
    }

    @IsTest 
    static void shouldMapCorrectValues() {
        LogEvent__e event = new LogEvent__e();
        event.Body__c = 'testing 123';
        event.Category__c = 'my category';
        event.Context__c = 'my context';
        event.Level__c = System.LoggingLevel.FINEST.name();
        event.LoggedAt__c = DateTime.now();
        event.LoggedBy__c = UserInfo.getUserId();
        event.LoggedFrom__c = LogEventTriggerTest.class?.getName();
        event.Ordinal__c = 100;
        event.RelatedRecordId__c = '001' + '0'.repeat(15);
        event.StackTrace__c = 'my stack trace';
        event.Transaction__c = 'my transaction';
        List<LogEvent__e> events = new List<LogEvent__e>{event};

        Test.startTest();
        EventBus.publish(events);
        Test.getEventBus()?.deliver();
        Test.stopTest();

        List<Log__c> logs = LogEventTriggerTest.getLogs();
        Assert.areEqual(events?.size(), logs?.size(), 'Wrong # of Logs');
        Log__c log = logs[0];
        Assert.areEqual(event?.Body__c, log?.Body__c, 'Wrong Body__c');
        Assert.areEqual(event?.Category__c, log?.Category__c, 'Wrong Category__c');
        Assert.areEqual(event?.Context__c, log?.Context__c, 'Wrong Context__c');
        Assert.areEqual(event?.Level__c, log?.Level__c, 'Wrong Level__c');
        Assert.areEqual(event?.LoggedAt__c, log?.LoggedAt__c, 'Wrong LoggedAt__c');
        Assert.areEqual(event?.LoggedBy__c, log?.LoggedBy__c, 'Wrong LoggedBy__c');
        Assert.areEqual(event?.LoggedFrom__c, log?.LoggedFrom__c, 'Wrong LoggedFrom__c');
        Assert.areEqual(event?.Ordinal__c, log?.Ordinal__c, 'Wrong Ordinal__c');
        Assert.areEqual(event?.RelatedRecordId__c, log?.RelatedRecordId__c, 'Wrong RelatedRecordId__c');
        Assert.areEqual(event?.StackTrace__c, log?.StackTrace__c, 'Wrong StackTrace__c');
        Assert.areEqual(event?.Transaction__c, log?.Transaction__c, 'Wrong Transaction__c');
    }

    // **** HELPER **** //
    @TestSetup 
    static void setup() {
        LogTestUtils.enableLogging(System.LoggingLevel.FINEST);
    }

    static List<Log__c> getLogs() {
        return [
            SELECT 
                Id, Body__c, Category__c, Context__c, Level__c, LoggedAt__c, LoggedBy__c, 
                LoggedFrom__c, Ordinal__c, RelatedRecordId__c, StackTrace__c, Transaction__c
            FROM Log__c
        ];
    }
}