force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <inlineHelpText>Details the current execution context when the log was generated.
Displays a System.Quiddity value: 
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_Quiddity.htm#topic-title</inlineHelpText>
    <label>Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <inlineHelpText>Indicates the severity of the log message. Values are derived from the System.LoggingLevel enum:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm</inlineHelpText>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>FINE</fullName>
            </value>
            <value>
                <fullName>FINER</fullName>
            </value>
            <value>
                <fullName>FINEST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/LoggedAt__c.field-meta.xml
<CustomField>
    <fullName>LoggedAt__c</fullName>
    <description>The Date/Time that the message was logged. This may differ slightly from the CreatedDate, depending on the publishing method</description>
    <label>Logged At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/LoggedBy__c.field-meta.xml
<CustomField>
    <fullName>LoggedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates the user that requested the Log. This may differ from the &quot;Created By&quot; user, if the log was published via platform event.</description>
    <label>Logged By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/RelatedRecordId__c.field-meta.xml
<CustomField>
    <fullName>RelatedRecordId__c</fullName>
    <description>The 18-digit Salesforce Id of the record most closely related to the current log.</description>
    <label>Related Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LogRelatedListController.cls
public abstract class LogRelatedListController {
	@AuraEnabled(cacheable=true)
	public static List<Log__c> getLogs(String recordId) {
		try {
			if (String.isBlank(recordId)) {
				throw new AuraHandledException('Missing Record Id');
			}
			return [
				SELECT
					Id,
					Body__c,
					Context__c,
					Level__c,
					LoggedAt__c,
					LoggedBy__c,
					LoggedBy__r.Name,
					Name,
					RelatedRecordId__c
				FROM Log__c
				WHERE RelatedRecordId__c = :recordId
				ORDER BY Id DESC
				LIMIT 50000
			];
		} catch (Exception error) {
			throw new AuraHandledException(error?.getMessage());
		}
	}

	@AuraEnabled(cacheable=true)
	public static Boolean hasAccess() {
		return SObjectType.Log__c?.isAccessible() == true;
	}
}